version: '3.8'
services:
  musika:
    image: plurdist/musika:latest
    container_name: blah
    volumes:
      - "c:/repos/AI-Music-Toolkit/docker/musika_outputs:/output"  # Only mount the output directory
    ports:
      - "7860:7860"  # Expose Gradio web UI (if applicable)
      - "6006:6006"  # Expose TensorBoard (if applicable)
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
