FROM tensorflow/tensorflow:2.11.1

RUN apt-get update && apt-get install -y \
    build-essential \
    libasound2-dev \
    libjack-dev \
    portaudio19-dev \
    cmake \
    git \
    python3-pip && \
    pip install --upgrade pip && \
    pip install dm-tree && \
    pip install -U magenta \
    pip install midi-ddsp \
    midi_ddsp_download_model_weights
