services:
  musika:
    image: plurdist/musika:latest
    container_name: musika-container
    volumes:
      - "${HOME}/musika_outputs:/output"  
    ports:
      - "7860:7860"
      - "6006:6006"  
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
